output "primaryhub_public_ip" {
  description = "Public Elastic IP for PrimaryHub + Envoy Gateway (Region A)"
  value       = aws_eip.eip_primaryhub.public_ip
}

output "secondaryhub_public_ip" {
  description = "Public Elastic IP for SecondaryHub Backup (Region B)"
  value       = aws_eip.eip_secondaryhub.public_ip
}

output "spoke1_public_ip" {
  description = "Public Elastic IP for Spoke1 Workloads (Region C)"
  value       = aws_eip.eip_spoke1.public_ip
}

output "spoke2_public_ip" {
  description = "Public Elastic IP for Spoke2 Workloads (Region D)"
  value       = aws_eip.eip_spoke2.public_ip
}

# Automatically generate prod.env configuration file
resource "local_file" "prod_env" {
  filename = "${path.module}/../prod.env"
  content  = <<-EOT
# Auto-generated by Terraform on ${timestamp()}
PRIMARYHUB_HOST="${aws_eip.eip_primaryhub.public_ip}"
SECONDARYHUB_HOST="${aws_eip.eip_secondaryhub.public_ip}"
SPOKE1_HOST="${aws_eip.eip_spoke1.public_ip}"
SPOKE2_HOST="${aws_eip.eip_spoke2.public_ip}"

SSH_USER="ubuntu"
SSH_KEY_PATH="${var.ssh_private_key_path}"
SSH_PORT="22"
WG_PORT="51820"
EOT
}
