##################################################################################################

################################################################
# This chart aggregates values from all sub-chart
################################################################

global:
  apiRoutePrefix: "/api/v1/01sbx"
  JWT_PUBLIC_JWKS: ""
  allowedIps:
    - "110.44.123.206"
    - "10."
    - "127.0.0.1"
    - "::1"
  ocm:
    enabled: true
    role: "hub" # "hub" or "spoke"
    primaryHub: "primaryhub"
    primaryHubIp: "10.9.9.10"
    secondaryHub: "secondaryhub"
    secondaryHubIp: "10.9.9.20"
    clusterSet: "sandbox-spokes"
    placementName: "sandbox-spoke-placement"
    spokes:
      - name: "spoke-us-east-1"
        region: "us-east-1"
        wireguardIp: "10.9.9.30"
      - name: "spoke-eu-central-1"
        region: "eu-central-1"
        wireguardIp: "10.9.9.40"
      - name: "spoke-us-west-1"
        region: "us-west-1"
        wireguardIp: "10.9.9.50"
################################################################
# Agent Gateway  values
################################################################
agentgateway:
  enabled: true
  namespace: agentgateway-system
  httproute:
    hostnames:
      # - api-sandbox.01security.com
      - 10.0.8.9
    backendService:
      name: sandbox-api-service
      port: 80
  gateway:
    gatewayClassName: agentgateway
    addresses:
      - value: 10.0.8.9
    listeners:
      - protocol: HTTP
        port: 80
        name: http
      # - protocol: HTTPS
      #   port: 443
      #   name: https
      #   tls:
      #     certificateRefs:
      #       - name: agentgateway-tls
      - protocol: TCP
        port: 5432
        name: postgresql
      - protocol: TCP
        port: 6379
        name: redis
      - protocol: TCP
        port: 5672
        name: rabbitmq-amqp
  policy:
    authenticationType: "jwt"
    jwtMode: "Strict"
    rateLimit:
      enabled: false
      requests: 500
      unit: "Minutes"
################################################################
# Agent Gateway Controller values
################################################################
agentgateway-controller:
  enabled: true
  controller:
    extraEnv:
      KGW_ENABLE_GATEWAY_API_EXPERIMENTAL_FEATURES: "true"
    image:
      pullPolicy: IfNotPresent
################################################################
# API Server component values
################################################################
apiServer:
  enabled: true
  namespace: opensandbox-system
  configMap:
    PYTHONUNBUFFERED: "1"
    APP_ENV: "production"
    SCANNER_IMAGE_PYTHON: "199012118961/01sandbox-scanner-python:dev"
    SCANNER_IMAGE_GO: "199012118961/01sandbox-scanner-go:dev"
    SCANNER_IMAGE_JAVA: "199012118961/01sandbox-scanner-java:dev"
    SCANNER_IMAGE_NODE: "199012118961/01sandbox-scanner-node:dev"
    SCANNER_IMAGE_K8S: "199012118961/01sandbox-scanner-k8s:dev"
    SCANNER_IMAGE_RUST: "199012118961/01sandbox-scanner-rust:dev"
    SCANNER_IMAGE_SHELL: "199012118961/01sandbox-scanner-shell:dev"
    SCANNER_IMAGE_CPP: "199012118961/01sandbox-scanner-cpp:dev"
    SCANNER_IMAGE_RUBY: "199012118961/01sandbox-scanner-ruby:dev"
    SCANNER_IMAGE_TERRAFORM: "199012118961/01sandbox-scanner-terraform:dev"
    SCANNER_IMAGE_DEFAULT: "199012118961/01sandbox-scanner-python:dev"
    PORT: "8000"
    BACKEND_URL_OPENSANDBOX: "http://opensandbox-server.opensandbox-system.svc.cluster.local"
    RATE_LIMIT_REQUESTS: "20"
    RATE_LIMIT_WINDOW_SECS: "60"
    GATEWAY_SECRET_NAME: "apikey"
    GATEWAY_SECRET_NAMESPACE: "agentgateway-system"
    GATEWAY_SECRET_KEY: "api-key"
    ALLOW_MOCK_KEYS: "true"
    JWT_EXPIRATION_MINUTES: "60"
    JWT_ISSUER: "01 Sandbox"
    JWT_ALGORITHM: "RS256"
    AUTH0_DOMAIN: "dev-axwc0ui527kw0c5d.us.auth0.com"
    AUTH0_AUDIENCE: "https://code-inspector-api"
    OPENSANDBOX_ROUTE_PREFIX: "{{ .Values.global.apiRoutePrefix }}"
    DASHBOARD_BACKENDS_JSON: '[{"id":"Z1_SANDBOX","name":"01 Sandbox","description":"Production-grade hardened cluster for secure code execution.","icon":"terminal","color":"indigo","baseUrl":"{{ .Values.global.apiRoutePrefix }}","documentationUrl":"{{ .Values.global.apiRoutePrefix }}/docs"}]'
    JWT_PUBLIC_JWKS: ""
    SENDGRID_FROM_EMAIL: "sandbox@01security.com"
    MAX_CONCURRENT_LANG_PODS: "10"
    MAX_CONCURRENT_LANG_SCANS: "10"
  secret:
    E2B_API_KEY: ""
    JWT_PRIVATE_KEY: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4cJ4r0fjpgQ8j
      Q93fNhi4Nmmy6aCqHcqw2EI4wynn6S9R56yLpbkF5OHKiynfeArbbpPUC5xcl7oy
      cQm6Lm7F4CB7pKaNMmoB3i30Qw3LBeq62CdDD2DiYJ7J9kMHdHZIOddO/H0cqlIV
      y1KmknQZh6qaSJG3mUtNa4edif0ItEfwe2Bz3I/XTBxG5vovU6Q0wLxwCKriLlJF
      yoyLj74SMsgMDYKSW4qqdkoFiLHtoZ7r7n1ccbYBE3LzsXCvojyQQGOH+vattl9V
      jngAj4ic2Pyoim1gWgz89HN43DVUPY1i57ZLpkCV8Fqcr2R6I2ADguXtO9v/ByF+
      /awzEqZ3AgMBAAECggEAPUofJYym3GFouF1LE2uUl1JtmWiNXTp9KnsStm4UNN6G
      PP9xlQ5DB7RhW78W8Q2g/f4m3aXmFdbNpwltJBNd+B9ca/nw5qbEF07PkoXdxYN3
      1xMRKPWpSlC1M4PEDmwjCik+ZR7+LFJk6J0iH/w23Gz6wj4vPgWQwm9jJ3S9QvCk
      fDm983jYXCAmG/kzJXS8BUIVtvoUXiDE2RdWxfaK9fqw5XOWlsK8gqLEkvG2HK2Y
      9UADhsWbAVlAmHE5rAjIwoG2+8ZrkoamV75jhM2KG78Gsp4/IHi34J5G4u/xFmCw
      wO4iEuKuojYBK1i98gH9Z9ZRRRRLF0/a2qfmRApqwQKBgQDwHZu1hkR8xZ19UtDJ
      prcj0bQXEa8U3GNM1o1H/Sj6TQOpb6Ge9LusiL2FOAcTFbpWHeRU6obDwOi44YQm
      Drp9qjiHy3FPCzAiy43MhWHDqdmDIROOMGNVntNr/Y3+MrcJIUBdigguYeFAnMa3
      8V6n3l25WR1qmnvxFt5ERMEbEQKBgQDEpCIa0j4alLJ5SgANtSoDnp9WMrHBj4ZK
      RfomAGLB1heBWefzYwWmodABgkVmKAFceQQnYLf6s/lVQ4zJo1hNVIujP37HAnFB
      YKPWcYD127u2utKQTZCJshTPU1o0hIFIu9MWQhctNK+ukRV+BdGWDsRY2t2TsswZ
      IDho5UJZBwKBgQCys+Z57+ay0cRHTEZVfb1ZbC3S6XdbWDaTLi7RwAkqV/z8sjcf
      /VZbrx0Vs8AYJRicFP0lcbJAqCbLyhM228lR00jlT7URterqSoJLD43WOGfInupV
      7Y9QXrdM7NUrtYThx5yGwT8bff9NviBrL7lZyDYKxtcMytKpeHKNbnolcQKBgF/T
      YG9Tn0ISznp+zlHfxA6pgRpfb/JUf+u3+DQGohm1vBSj/H3F9p4CYrwpgKpMuoUW
      0ChkYKPCirG7TmOAv2pH1hiCu8Q9c3WZo53ACElHgE2G80+xDMudRbjW9LF9FQed
      yDsjj+nOsAJQ33lfWohWv+ZRGgN88SsZYYP0nQWHAoGBAIigNpk8Mrx0aQWJQ97H
      2d/EFgneIQKYzrLeLzt8+WCed/mAesDGL21TI7blZYtSq9Gba6M8VnQhnjk9yul9
      RM6PSdDPTe6f01TBU71sMsjPtAxCrsonn/ISzHatpJ9vAUmmHXK3/blplEc7Fhkl
      kYVZfPw/fIDkPCKJx7E8mCmM
      -----END PRIVATE KEY-----
    JWT_PUBLIC_JWKS: '{"keys": [{"kty": "RSA", "use": "sig", "kid": "code-inspector-key-01", "alg": "RS256", "n": "uHCeK9H46YEPI0Pd3zYYuDZpsumgqh3KsNhCOMMp5-kvUeesi6W5BeThyosp33gK226T1AucXJe6MnEJui5uxeAge6SmjTJqAd4t9EMNywXqutgnQw9g4mCeyfZDB3R2SDnXTvx9HKpSFctSppJ0GYeqmkiRt5lLTWuHnYn9CLRH8Htgc9yP10wcRub6L1OkNMC8cAiq4i5SRcqMi4--EjLIDA2CkluKqnZKBYix7aGe6-59XHG2ARNy87Fwr6I8kEBjh_r2rbZfVY54AI-InNj8qIptYFoM_PRzeNw1VD2NYue2S6ZAlfBanK9keiNgA4Ll7Tvb_wchfv2sMxKmdw", "e": "AQAB"}]}'
    SENDGRID_API_KEY: ""
  sealedSecrets:
    enabled: false
  deployment:
    replicaCount: 1
    image:
      repository: 199012118961/01sandbox-api
      tag: "dev"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
  service:
    type: NodePort
    port: 80
    targetPort: 8000
    nodePort: 30080
  ingress:
    enabled: false
    className: nginx
    host: api-sandbox.01security.com
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  postgresql:
    enabled: true
    host: "postgresql-service"
    port: 5432
    user: "postgres"
    password: "password123"
    database: "apikeys"
    storage: "5Gi"
    storageClassName: "standard"
  redis:
    enabled: true
    host: "redis-service"
    port: 6379
    password: ""
  rabbitmq:
    enabled: true
    host: "rabbitmq-service"
    port: 5672
    user: "admin"
    password: "changeme"
    maxQuickScanWorkers: "1"
    maxRepoScanWorkers: "1"
################################################################
# MetalLB component values
################################################################
metallb:
  enabled: true
  namespace: metallb-system
  ipAddressPool:
    addresses:
      # - 172.18.0.200-172.18.0.250
      - 10.0.8.9-10.0.8.9
  l2Advertisement:
    enabled: true

################################################################
# OpenSandbox component values
################################################################
opensandbox:
  enabled: true
  namespace: opensandbox-system
  controller:
    replicaCount: 1
    image:
      repository: 199012118961/01sandbox-opensandbox-controller
      tag: "dev"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  server:
    replicaCount: 1
    sandboxImage: "199012118961/01sandbox-codeinterpreter:dev"
    scannerImagePython: "199012118961/01sandbox-scanner-python:dev"
    scannerImageGo: "199012118961/01sandbox-scanner-go:dev"
    scannerImageJava: "199012118961/01sandbox-scanner-java:dev"
    scannerImageNode: "199012118961/01sandbox-scanner-node:dev"
    scannerImageK8s: "199012118961/01sandbox-scanner-k8s:dev"
    scannerImageRust: "199012118961/01sandbox-scanner-rust:dev"
    scannerImageCpp: "199012118961/01sandbox-scanner-cpp:dev"
    scannerImageRuby: "199012118961/01sandbox-scanner-ruby:dev"
    sandboxCpu: "200m"
    sandboxMemory: "256Mi"
    sandboxCreateTimeoutSeconds: 600
    autoTerminationSeconds: 0
    runtimeClassName: "gvisor"
    image:
      repository: 01community/01sandbox-opensandbox-server
      tag: "v0.7.10-ocm"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    storage:
      enabled: true
      pvcName: "scan-pvc"
      size: "10Gi"
      accessMode: "ReadWriteMany"
      mountPath: "/data"
      storageClassName: "standard"
################################################################
# OpenSandbox Resource Pool component values
################################################################
opensandboxResourcePool:
  enabled: false
  namespace: opensandbox-system
  pool:
    name: my-sandbox-pool
    container:
      image: "199012118961/01sandbox-codeinterpreter:dev"
      ports:
        - containerPort: 44772
        - containerPort: 54321
    capacitySpec:
      bufferMin: 3
      bufferMax: 10
      poolMin: 1
      poolMax: 50
###############################################################
# Prometheus component values
###############################################################
prometheus:
  enabled: false
  namespace: monitoring
  apiServerNamespace: opensandbox-system
  apiServerServiceName: sandbox-api-service
  apiServerPort: 80
  agentgatewayNamespace: agentgateway-system
  agentgatewayServiceName: agentgateway-proxy
  agentgatewayPort: 80
  replicaCount: 1
  ingressRoute:
    enabled: true
  ingressHostnames:
    - api-sandbox.01security.com
    - 10.0.8.9
  ingressPath: "/prometheus"
  image:
    repository: prom/prometheus
    tag: "v2.54.1"
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    pvcName: "prometheus-pvc"
  service:
    type: ClusterIP
    port: 9090
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
###############################################################
# Grafana component values
###############################################################
grafana:
  enabled: false
  namespace: monitoring
  prometheusNamespace: monitoring
  prometheusServiceName: prometheus-service
  prometheusPort: 9090
  replicaCount: 1
  ingressRoute:
    enabled: true
  ingressHost: "api-sandbox.01security.com"
  ingressHostnames:
    - api-sandbox.01security.com
    - 10.0.8.9
  ingressPath: "/grafana"
  image:
    repository: grafana/grafana
    tag: "11.1.0"
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    pvcName: "grafana-pvc"
  service:
    type: NodePort
    port: 3000
    nodePort: 32000
  adminPassword: "admin"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
###############################################################
# Sealed Secrets subchart controller values
###############################################################
sealed-secrets:
  enabled: false
