{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sandbox-api-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- if .Values.sealedSecrets.encryptedData.E2B_API_KEY }}
    E2B_API_KEY: {{ .Values.sealedSecrets.encryptedData.E2B_API_KEY | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.encryptedData.JWT_PRIVATE_KEY }}
    JWT_PRIVATE_KEY: {{ .Values.sealedSecrets.encryptedData.JWT_PRIVATE_KEY | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.encryptedData.JWT_PUBLIC_JWKS }}
    JWT_PUBLIC_JWKS: {{ .Values.sealedSecrets.encryptedData.JWT_PUBLIC_JWKS | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.encryptedData.SENDGRID_API_KEY }}
    SENDGRID_API_KEY: {{ .Values.sealedSecrets.encryptedData.SENDGRID_API_KEY | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.encryptedData.PG_PASSWORD }}
    PG_PASSWORD: {{ .Values.sealedSecrets.encryptedData.PG_PASSWORD | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.encryptedData.REDIS_PASSWORD }}
    REDIS_PASSWORD: {{ .Values.sealedSecrets.encryptedData.REDIS_PASSWORD | quote }}
    {{- end }}
    {{- if .Values.sealedSecrets.encryptedData.RABBITMQ_PASSWORD }}
    RABBITMQ_PASSWORD: {{ .Values.sealedSecrets.encryptedData.RABBITMQ_PASSWORD | quote }}
    {{- end }}
{{- end }}
