{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sandbox-api-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    E2B_API_KEY: {{ .Values.sealedSecrets.encryptedData.E2B_API_KEY | quote }}
    JWT_PRIVATE_KEY: {{ .Values.sealedSecrets.encryptedData.JWT_PRIVATE_KEY | quote }}
    JWT_PUBLIC_JWKS: {{ .Values.sealedSecrets.encryptedData.JWT_PUBLIC_JWKS | quote }}
    SENDGRID_API_KEY: {{ .Values.sealedSecrets.encryptedData.SENDGRID_API_KEY | quote }}
    PG_PASSWORD: {{ .Values.sealedSecrets.encryptedData.PG_PASSWORD | quote }}
    REDIS_PASSWORD: {{ .Values.sealedSecrets.encryptedData.REDIS_PASSWORD | quote }}
    RABBITMQ_PASSWORD: {{ .Values.sealedSecrets.encryptedData.RABBITMQ_PASSWORD | quote }}
{{- end }}
