{{- if not .Values.sealedSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  E2B_API_KEY: {{ .Values.secret.E2B_API_KEY | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secret.JWT_PRIVATE_KEY | b64enc | quote }}
  JWT_PUBLIC_JWKS: {{ .Values.secret.JWT_PUBLIC_JWKS | b64enc | quote }}
  SENDGRID_API_KEY: {{ .Values.secret.SENDGRID_API_KEY | b64enc | quote }}
  PG_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | b64enc | quote }}
{{- end }}
