{{- if .Values.multiCluster.enabled }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.multiCluster.placementName | default "sandbox-spoke-placement" }}
  namespace: {{ .Values.namespace }}
spec:
  clusterSets:
    - {{ .Values.multiCluster.clusterSet | default "sandbox-spokes" }}
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            sandbox-workload-capable: "true"
            runtime.gvisor: "true"
            runtime.kata: "true"
{{- end }}
