# Default values for grafana
namespace: monitoring

prometheusNamespace: monitoring
prometheusServiceName: prometheus-service
prometheusPort: 9090

replicaCount: 1

ingressRoute:
  enabled: true
ingressHost: "api-sandbox.01security.com"
ingressHostnames:
  - api-sandbox.01security.com
  - 10.0.10.100
ingressPath: "/grafana"


image:
  repository: grafana/grafana
  tag: "11.1.0"
  pullPolicy: IfNotPresent

persistence:
  enabled: false
  pvcName: "grafana-pvc"



service:
  type: NodePort
  port: 3000
  nodePort: 32000

adminPassword: "admin"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
