{{- if and .Values.global .Values.global.ocm .Values.global.ocm.enabled (eq (default "hub" .Values.global.ocm.role) "hub") }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ default "sandbox-spoke-placement" .Values.global.ocm.placementName }}
  namespace: {{ default "opensandbox-system" .Values.opensandbox.namespace }}
  labels:
    {{- include "codeInspector.labels" . | nindent 4 }}
spec:
  clusterSets:
    - {{ default "sandbox-spokes" .Values.global.ocm.clusterSet }}
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            sandbox-workload-capable: "true"
            runtime.gvisor: "true"
            runtime.kata: "true"
{{- end }}
